import BigHrushovski

#print axioms BigHrushovski.FiniteGraph.edgeCount_supermodular
#print axioms BigHrushovski.FiniteGraph.predim_submodular
#print axioms BigHrushovski.Predimension.strong_refl
#print axioms BigHrushovski.Predimension.strong_restrict
#print axioms BigHrushovski.Predimension.strong_of_dClosed
#print axioms BigHrushovski.Predimension.strong_trans
#print axioms BigHrushovski.Predimension.strong_inter

#print axioms BigHrushovski.Predimension.delta_inter_le_of_strong
#print axioms BigHrushovski.Predimension.dclosed_trans
#print axioms BigHrushovski.Predimension.dclosed_inter

#print axioms BigHrushovski.Predimension.strong_intersectFamily
#print axioms BigHrushovski.Predimension.strongHull_strong
#print axioms BigHrushovski.Predimension.subset_strongHull
#print axioms BigHrushovski.Predimension.strongHull_least
#print axioms BigHrushovski.Predimension.exists_least_strong_hull

#print axioms BigHrushovski.Predimension.globallyStrong_inter
#print axioms BigHrushovski.Predimension.strongHull_global
#print axioms BigHrushovski.Predimension.strongHull_least_global
#print axioms BigHrushovski.Predimension.strongHull_eq_of_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.contains_finite
#print axioms BigHrushovski.Predimension.StrongExhaustion.subset_closure
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_least_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_eq_strongHull
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_mono
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_idempotent
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_eq_self_of_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.global_of_closure_eq_self

#print axioms BigHrushovski.Predimension.globallyStrong_of_strong_in_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.equal_closure_of_minimal_choice
#print axioms BigHrushovski.Predimension.StrongExhaustion.minimal_extension_of_choice

#print axioms BigHrushovski.Predimension.StrongExhaustion.exists_minimal_choice
#print axioms BigHrushovski.Predimension.StrongExhaustion.exists_minimal_strong_extension

#print axioms BigHrushovski.Predimension.StrongExhaustion.finite_minimal_decomposition

#print axioms BigHrushovski.Predimension.StrongExhaustion.finite_minimal_decomposition_of_strong

#print axioms BigHrushovski.FiniteGraph.edgesWithin_insert_split
#print axioms BigHrushovski.FiniteGraph.backEdges_disjoint
#print axioms BigHrushovski.FiniteGraph.edge_count_insert
#print axioms BigHrushovski.FiniteGraph.predim_insert
#print axioms BigHrushovski.FiniteGraph.backEdges_card_le_two
#print axioms BigHrushovski.FiniteGraph.strong_insert_of_two_backEdges
#print axioms BigHrushovski.FiniteGraph.closure_insert_of_two_backEdges
