import BigHrushovski

#print axioms BigHrushovski.FiniteGraph.edgeCount_supermodular
#print axioms BigHrushovski.FiniteGraph.predim_submodular
#print axioms BigHrushovski.Predimension.strong_refl
#print axioms BigHrushovski.Predimension.strong_restrict
#print axioms BigHrushovski.Predimension.strong_of_dClosed
#print axioms BigHrushovski.Predimension.strong_trans
#print axioms BigHrushovski.Predimension.strong_inter

#print axioms BigHrushovski.Predimension.delta_inter_le_of_strong
#print axioms BigHrushovski.Predimension.dclosed_trans
#print axioms BigHrushovski.Predimension.dclosed_inter

#print axioms BigHrushovski.Predimension.strong_intersectFamily
#print axioms BigHrushovski.Predimension.strongHull_strong
#print axioms BigHrushovski.Predimension.subset_strongHull
#print axioms BigHrushovski.Predimension.strongHull_least
#print axioms BigHrushovski.Predimension.exists_least_strong_hull

#print axioms BigHrushovski.Predimension.globallyStrong_inter
#print axioms BigHrushovski.Predimension.strongHull_global
#print axioms BigHrushovski.Predimension.strongHull_least_global
#print axioms BigHrushovski.Predimension.strongHull_eq_of_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.contains_finite
#print axioms BigHrushovski.Predimension.StrongExhaustion.subset_closure
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_least_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_eq_strongHull
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_mono
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_idempotent
#print axioms BigHrushovski.Predimension.StrongExhaustion.closure_eq_self_of_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.global_of_closure_eq_self

#print axioms BigHrushovski.Predimension.globallyStrong_of_strong_in_global
#print axioms BigHrushovski.Predimension.StrongExhaustion.equal_closure_of_minimal_choice
#print axioms BigHrushovski.Predimension.StrongExhaustion.minimal_extension_of_choice

#print axioms BigHrushovski.Predimension.StrongExhaustion.exists_minimal_choice
#print axioms BigHrushovski.Predimension.StrongExhaustion.exists_minimal_strong_extension

#print axioms BigHrushovski.Predimension.StrongExhaustion.finite_minimal_decomposition

#print axioms BigHrushovski.Predimension.StrongExhaustion.finite_minimal_decomposition_of_strong

#print axioms BigHrushovski.Predimension.FiniteStrongCover.chosenContainer_contains
#print axioms BigHrushovski.Predimension.FiniteStrongCover.chosenContainer_global
#print axioms BigHrushovski.Predimension.FiniteStrongCover.closure_global
#print axioms BigHrushovski.Predimension.FiniteStrongCover.closure_least_global
#print axioms BigHrushovski.Predimension.FiniteStrongCover.closure_idempotent
#print axioms BigHrushovski.Predimension.FiniteStrongCover.closure_eq_exhaustion
#print axioms BigHrushovski.Predimension.CountableStrongCover.stage_global
#print axioms BigHrushovski.Predimension.CountableStrongCover.stage_step
#print axioms BigHrushovski.Predimension.CountableStrongCover.stage_monotone
#print axioms BigHrushovski.Predimension.CountableStrongCover.stage_covers
#print axioms BigHrushovski.Predimension.CountableStrongCover.exists_strong_exhaustion
#print axioms BigHrushovski.Predimension.CountableStrongCover.exhaustion_closure_eq_cover

#print axioms BigHrushovski.Predimension.StrongExhaustion.toFiniteStrongCover
#print axioms BigHrushovski.Predimension.finite_cover_iff_strong_exhaustion_of_surjective

#print axioms BigHrushovski.FiniteGraph.edgesWithin_insert_split
#print axioms BigHrushovski.FiniteGraph.backEdges_disjoint
#print axioms BigHrushovski.FiniteGraph.edge_count_insert
#print axioms BigHrushovski.FiniteGraph.predim_insert
#print axioms BigHrushovski.FiniteGraph.backEdges_card_le_two
#print axioms BigHrushovski.FiniteGraph.strong_insert_of_two_backEdges
#print axioms BigHrushovski.FiniteGraph.closure_insert_of_two_backEdges

#print axioms BigHrushovski.GraphOn.mem_edgesWithin_iff
#print axioms BigHrushovski.GraphOn.edgesWithin_union_subset
#print axioms BigHrushovski.GraphOn.edgesWithin_inter
#print axioms BigHrushovski.GraphOn.edgeCount_supermodular
#print axioms BigHrushovski.GraphOn.predim_submodular
#print axioms BigHrushovski.GraphOn.finiteView_edgesWithin
#print axioms BigHrushovski.GraphOn.predim_finiteView

#print axioms BigHrushovski.GraphOn.isStrong_finiteView_iff
#print axioms BigHrushovski.GraphOn.finiteView_backEdges
#print axioms BigHrushovski.GraphOn.backEdges_card_le_two
#print axioms BigHrushovski.GraphOn.closure_insert_of_two_backEdges

#print axioms BigHrushovski.GraphOn.pair_mem_backEdges
#print axioms BigHrushovski.GraphOn.backEdge_exists_oldNeighbour
#print axioms BigHrushovski.GraphOn.backEdges_eq_neighbour_image
#print axioms BigHrushovski.GraphOn.neighbour_pair_injOn
#print axioms BigHrushovski.GraphOn.backEdges_card_eq_oldNeighbours_card
#print axioms BigHrushovski.GraphOn.oldNeighbours_card_le_two
#print axioms BigHrushovski.GraphOn.closure_insert_of_two_oldNeighbours

#print axioms BigHrushovski.Predimension.StrongChain.strong_stages
#print axioms BigHrushovski.Predimension.StrongChain.stage_monotone
#print axioms BigHrushovski.Predimension.StrongChain.contains_finite
#print axioms BigHrushovski.Predimension.StrongChain.stage_global
#print axioms BigHrushovski.Predimension.StrongChain.toFiniteStrongCover
#print axioms BigHrushovski.Predimension.exists_strong_chain_iff_exhaustion

#print axioms BigHrushovski.GraphOn.edgesWithin_union_eq
#print axioms BigHrushovski.GraphOn.predim_modular_of_noCross
#print axioms BigHrushovski.GraphOn.noCross_restrict_right
#print axioms BigHrushovski.GraphOn.strong_left_of_noCross
#print axioms BigHrushovski.GraphOn.strong_right_of_noCross

#print axioms BigHrushovski.GraphOn.twoSparse_of_strong_extension
#print axioms BigHrushovski.GraphOn.noCross_inter
#print axioms BigHrushovski.GraphOn.twoSparse_union_of_noCross
#print axioms BigHrushovski.GraphOn.twoSparse_union_of_noCross_right

#print axioms BigHrushovski.GraphOn.freeJoin_adj_left
#print axioms BigHrushovski.GraphOn.freeJoin_adj_right
#print axioms BigHrushovski.GraphOn.freeJoin_edgesWithin_left
#print axioms BigHrushovski.GraphOn.freeJoin_edgesWithin_right
#print axioms BigHrushovski.GraphOn.freeJoin_noCross
#print axioms BigHrushovski.GraphOn.freeJoin_predim_left
#print axioms BigHrushovski.GraphOn.freeJoin_predim_right

#print axioms BigHrushovski.GraphOn.freeJoin_strong_base_right
#print axioms BigHrushovski.GraphOn.freeJoin_strong_base_left
#print axioms BigHrushovski.GraphOn.freeJoin_strong_left
#print axioms BigHrushovski.GraphOn.freeJoin_strong_right
#print axioms BigHrushovski.GraphOn.freeJoin_twoSparse
#print axioms BigHrushovski.GraphOn.freeJoin_strong_amalgam

#print axioms BigHrushovski.TaggedAmalgam.leftTag_injective
#print axioms BigHrushovski.TaggedAmalgam.rightTag_injective
#print axioms BigHrushovski.TaggedAmalgam.leftTag_eq_rightTag
#print axioms BigHrushovski.TaggedAmalgam.freeGraph_left
#print axioms BigHrushovski.TaggedAmalgam.freeGraph_right
#print axioms BigHrushovski.TaggedAmalgam.freeGraph_no_cross
#print axioms BigHrushovski.TaggedAmalgam.freeGraph_amalgam

#print axioms BigHrushovski.GraphOn.isEdge_image_iff
#print axioms BigHrushovski.GraphOn.edgesWithin_image
#print axioms BigHrushovski.GraphOn.card_edgesWithin_image
#print axioms BigHrushovski.GraphOn.predim_image
